### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by FelineAstronomer** [aria1th/litematica-printer#41] opened 2022-12-15 00:23 UTC
Looks like the current version doesn't support 1.19.3 - the game crashes when attempting to use any printer functionality. Running on 1.19.3 with the latest version of litematica and fabric for 1.19.3 as of this post.

**Comment by Notoriousi** [comment] 2022-12-16 14:31
Crash report:
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1799.method_7987(net.minecraft.class_1799, net.minecraft.class_1799)'
	at io.github.eatmyvenom.litematicin.utils.InventoryUtils.areItemsExact(InventoryUtils.java:111)
	at io.github.eatmyvenom.litematicin.utils.InventoryUtils.requiresSwap(InventoryUtils.java:143)
	at io.github.eatmyvenom.litematicin.utils.InventoryUtils.swapToItem(InventoryUtils.java:168)
	at io.github.eatmyvenom.litematicin.utils.Printer.doSchematicWorldPickBlock(Printer.java:147)
	at io.github.eatmyvenom.litematicin.utils.Printer.doPrinterAction(Printer.java:1187)
	at fi.dy.masa.litematica.util.WorldUtils.handler$eka000$onDoEasyPlaceAction(WorldUtils.java:2717)
	at fi.dy.masa.litematica.util.WorldUtils.doEasyPlaceAction(WorldUtils.java)
	at fi.dy.masa.litematica.util.WorldUtils.handleEasyPlace(WorldUtils.java:411)
	at fi.dy.masa.litematica.event.KeyCallbacks$KeyCallbackHotkeys.onKeyAction(KeyCallbacks.java:268)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.triggerKeyAction(KeybindMulti.java:185)
	at fi.dy.masa.malilib.hotkeys.KeybindMulti.updateIsPressed(KeybindMulti.java:145)
	at fi.dy.masa.malilib.event.InputEventHandler.checkKeyBindsForChanges(InputEventHandler.java:270)
	at fi.dy.masa.malilib.event.InputEventHandler.onMouseClick(InputEventHandler.java:172)
	at net.minecraft.class_312.handler$fck000$hookOnMouseClick(class_312.java:3556)
	at net.minecraft.class_312.method_1601(class_312.java:54)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

**Comment by aria1th** [comment] 2022-12-18 12:27
Please check https://github.com/aria1th/litematica-printer/releases/tag/6.8.0-v1.19.3 !

**Comment by Notoriousi** [comment] 2022-12-18 12:47
Doesn't make it crash, but now you take damage while using the printer (both in survival and creative). all default settings used

**Comment by aria1th** [comment] 2022-12-18 12:58
....what??? I don't use any damage related function or code in printer itself, so could it be some kind of... anticheat?

**Comment by Notoriousi** [comment] 2022-12-18 13:15
I'm not sure. I tested it in singleplayer with only malilib, litematica, printer and fabricapi enabled to make sure it's not another mod causing it.
![2022-12-18_14 15 36](https://user-images.githubusercontent.com/94121814/208300441-01c44619-2882-44b4-a16a-deb28878bba0.png)

**Comment by aria1th** [comment] 2022-12-18 13:27
does it happen in creative mode too? and is `printerBreakBlock` option enabled? and is it instant kill?

**Comment by Notoriousi** [comment] 2022-12-18 13:30
Yes i tested it first in creative. It's like falling in the void, it takes 5 hits to kill but it remembers previous damage taken. PrinterBreakBlocks is disabled (false)

Edit: It seems to mainly happen when placing upside down stairs

**Comment by aria1th** [comment] 2022-12-18 14:13
that's really weird... can you try with `fakeRotation` off? mojang maybe added some weird feature related to it

**Comment by Notoriousi** [comment] 2022-12-18 20:40
Without fakeRotation the issue is not there

**Comment by FelineAstronomer** [comment] 2022-12-19 19:58
I also can confirm fake rotation causes self damage - in singleplayer. Otherwise this appears to be working reasonably well.

In multiplayer, fake rotation doesn't cause self damage, but it doesn't really work and can cause the user to glitch around.

**Comment by luisccl** [comment] 2022-12-20 20:12
it casues self damage in multiplayer for me aswell. fake rotation works for me in multiplayer but at some angles (limited testing) will cause self damage, and sometimes it does not and places everything correctly.

**Comment by aria1th** [comment] 2022-12-21 05:18
Well I'm not sure but mojang definitely added some weird stuff.... huh....

**Comment by aria1th** [comment] 2022-12-21 05:34
@luisccl  @FelineAstronomer @Notoriousi Fixed in https://github.com/aria1th/litematica-printer/commit/39a377fc6f3112043c2abc54a3d0658d3d0e5516 (should)
can you try with automatic build artifact? just to make sure before I make release

**Comment by Notoriousi** [comment] 2022-12-21 10:35
Seems to have fixed it for me in both survival and creative. Muntiplayer untested

**Closed as completed** 2022-12-21 13:28 UTC
